### ISSUE TITLE
Feature: [DungeonSystem] 결과창 UI 구현

### ISSUE THREAD

**Issue by Nameless1004** [KIA-PROGRAMMING-38/Dungreed#35]
# 설명
던전에서 죽었을 때, 나갈 때 UI를 구현합니다.
* 지금까지 먹었던 아이템, 골드, 진행 시간, 적 처치 정보, (죽었을 때) 나를 죽인 적의 이름이 나타납니다.
* 결과 창이 나오고 일정 시간이 지나면 문이 나와서 아이템들을 빨아들입니다.

**Comment by ChoiSeonMun** [comment]
결과창 UI 대신에 전투 콘텐츠 쪽으로 더 풍성하게 구성
